<template>
  <div class="max-w-7xl mx-auto p-4">
    <BaseTable
      :columns="tableMetadata.columns"
      :data="processedEmployeeData"
      :left-fixed="tableMetadata.leftFixed"
      :right-fixed="tableMetadata.rightFixed"
      :show-summary="true"
    />
  </div>
</template>

<script lang="ts" setup>
import { computed } from 'vue'
import BaseTable from '@/components/BaseTable.vue'

// Your original employee data
const rawEmployeeData = [
    {
      id: '6d23b600-557f-f1cd-6e86-ca878a7ad16d',
      name: 'Худайбердиев Беҳзод Дилшод ўғли',
      name1: 'XUDAYBERDIYEV BEHZOD DILSHOD O‘G‘LI',
      position: 'кичик дастурчиси',
      structure: '1',
      org_id: 303465075,
      num: null,
      order_date: null,
      main_image: 'https://api.smart-office.uz/uploads/files/ff808181ea1e3d1c94ff058b',
      type1: 'Фоизсиз қарз бериш',
      type2: 8,
      type: 'MATERIAL_SUPPORT',
      doc_date: '15.04.2025',
      doc_date1: '15.04.2025',
      gr_name: 2025,
      start_work_date: null,
      updated: '15.04.2025 14:59:34',
      created: '15.04.2025 14:22:01',
      department: '141-бўлим  ("Call24" бўлими) ',
      staff_signed_at: '15.04.2025 14:22:21',
      header_signed_at: '15.04.2025 14:22:21',
      submission_signed_at: null,
      doc_link:
        'https://hujjat.smart-office.uz/document?id=5b2f6cf0-acce-46f3-9992-dda73116c879&pin=rB57qD93&_target=blank',
      doc_link_c:
        'forms/material-support-contract-modified?application_id=6d23b600-557f-f1cd-6e86-ca878a7ad16d&_target=modal_1200',
      doc_link_modal:
        'forms/applications-accounting-modified-form/6d23b600-557f-f1cd-6e86-ca878a7ad16d?_target=modal_1200',
      s1: '15.04.2025',
      s2: '15.04.2025',
      s3: 'имзоланмaган',
      c1: 'ҳужжат мавжуд эмас !',
      c2: 'ҳужжат мавжуд эмас !',
      sum_s1: 6460000,
      period_s1: '5',
      sum_s2: 6460000,
      period_s2: '5',
      doc_status: 2,
      created_at: '15-04-2025',
      staff_pinfl: '33105985580014',
      remainder: 1292000,
      procent_remainder: 20,
      part: 5168000,
      procent_part: 80,
    },
    {
      id: '6003ae90-e8ad-deb4-93a0-d0aa175654f7',
      name: 'Худайбердиев Беҳзод Дилшод ўғли',
      name1: 'XUDAYBERDIYEV BEHZOD DILSHOD O‘G‘LI',
      position: 'кичик дастурчиси',
      structure: '1',
      org_id: 303465075,
      num: null,
      order_date: null,
      main_image: 'https://api.smart-office.uz/uploads/files/ff808181ea1e3d1c94ff058b',
      type1: 'Фоизсиз қарз бериш',
      type2: 8,
      type: 'MATERIAL_SUPPORT',
      doc_date: '17.04.2024',
      doc_date1: '17.04.2024',
      gr_name: 2024,
      start_work_date: null,
      updated: '19.04.2024 03:49:57',
      created: '17.04.2024 15:01:28',
      department: '141-бўлим  ("Call24" бўлими) ',
      staff_signed_at: '17.04.2024 15:02:14',
      header_signed_at: '18.04.2024 11:22:22',
      submission_signed_at: null,
      doc_link:
        'https://hujjat.smart-office.uz/document?id=dc738484-b870-4331-8b98-dab4293ad2d3&pin=tR63cN14&_target=blank',
      doc_link_c:
        'https://hujjat.smart-office.uz/document?id=937001b3-80ae-439e-9a0c-8ea6a22fb370&pin=uW59mK85&_target=blank',
      doc_link_modal:
        'forms/applications-accounting-modified-form/6003ae90-e8ad-deb4-93a0-d0aa175654f7?_target=modal_1200',
      s1: '17.04.2024',
      s2: '18.04.2024',
      s3: 'имзоланмaган',
      c1: '18.04.2024',
      c2: '18.04.2024',
      sum_s1: 9000000,
      period_s1: '12',
      sum_s2: 9000000,
      period_s2: '12',
      doc_status: 3,
      created_at: '17-04-2024',
      staff_pinfl: '33105985580014',
      remainder: 0,
      procent_remainder: 0,
      part: 9000000,
      procent_part: 100,
    },
    {
      id: '35ddfafd-91de-ee1d-f845-9cf10a4aba77',
      name: 'Худайбердиев Беҳзод Дилшод ўғли',
      name1: 'XUDAYBERDIYEV BEHZOD DILSHOD O‘G‘LI',
      position: 'кичик дастурчиси',
      structure: '1',
      org_id: 303465075,
      num: null,
      order_date: null,
      main_image: 'https://api.smart-office.uz/uploads/files/ff808181ea1e3d1c94ff058b',
      type1: 'Фоизсиз қарз бериш',
      type2: 8,
      type: 'MATERIAL_SUPPORT',
      doc_date: '15.04.2024',
      doc_date1: '15.04.2024',
      gr_name: 2024,
      start_work_date: null,
      updated: '17.04.2024 15:08:22',
      created: '15.04.2024 10:08:36',
      department: '141-бўлим  ("Call24" бўлими) ',
      staff_signed_at: '15.04.2024 10:11:30',
      header_signed_at: '17.04.2024 15:08:21',
      submission_signed_at: null,
      doc_link:
        'https://hujjat.smart-office.uz/document?id=9357e9de-40ac-4621-a080-2f6a4f9a2cac&pin=hH28hW84&_target=blank',
      doc_link_c:
        'https://hujjat.smart-office.uz/document?id=e653f6ad-9667-4bbc-910a-79ea99940ddc&pin=kR67lR59&_target=blank',
      doc_link_modal:
        'forms/applications-accounting-modified-form/35ddfafd-91de-ee1d-f845-9cf10a4aba77?_target=modal_1200',
      s1: '15.04.2024',
      s2: '17.04.2024',
      s3: 'имзоланмaган',
      c1: 'имзоланмaган',
      c2: 'имзоланмaган',
      sum_s1: 24000000,
      period_s1: '24',
      sum_s2: 24000000,
      period_s2: '24',
      doc_status: null,
      created_at: '15-04-2024',
      staff_pinfl: '33105985580014',
      remainder: null,
      procent_remainder: null,
      part: null,
      procent_part: null,
    },
]

// Process the data to add row numbers and any missing fields
const processedEmployeeData = computed(() => {
  return rawEmployeeData.map((employee, index) => ({
    ...employee,
    _rownum: index + 1,
    id: `emp_${index}`,
  }))
})

const tableMetadata = {
  id: 5376,
  level: 1,
  title: 'Ҳужжатлар рўйхати',
  header: 'Ҳужжатлар рўйхати ',
  isPublic: null,
  sortable: false,
  groupingField: 'gr_name',
  refreshTimeout: 0,
  fitHeightToParent: false,
  height: null,
  leftFixed: null,
  rightFixed: 4,
  searchLink: null,
  searchPlaceholder: null,
  paginationSize: 15,
  name: 'applications-accounting-modified',
  js: "\n\nthis.$api.post('v1/audit/table?tableName=applications-accounting-modified')",
  css: '.enlarged_picture {\n  color: rgb(255, 255, 255); \n  background-color: rgba(0, 0, 0, 0.8); \n  cursor: pointer; \n  padding: 10px; \n  z-index: 9998; box-sizing: border-box;\n  position: fixed; top: 0px; left: 0px; \n  width: 100%; height: 100%; \n  -webkit-box-align: center; -webkit-box-pack: center; \n  display: flex; align-items: center; justify-content: center; \n  transition: opacity 0.3s ease 0s; \n}\n.enlarged_picture > img {\n  border-radius: 2px; \n  position: absolute; top: 14; left: 0; \n  width: 100%; max-width: 100%; height: 100%; \n  height: auto; max-height: calc(100vh - 140px); \n  border-radius: 2px; object-fit: contain; \n  z-index: 11; cursor: pointer; \n  display: block; margin: 0px auto; user-select: none;\n}',
  dataSourceType: 'SQL',
  dataUrl: null,
  userColumns: '',
  datasource: 'project',
  columns: [
    {
      dataField: '_rownum',
      sortOrder: 10,
      link: null,
      title: '№',
      sumType: null,
      hint: null,
      width: '20',
      formatCondition: '',
      formatColor: '',
      formatBackgroundColor: '',
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'center',
      footerAlign: 'center',
      cellFormat:
        'return {\ntemplate: `\n<template>\n <div>\n       <div v-if="data.num == null" style="font-weight: 700">\n         ${value}\n       </div>\n       <div  v-else>\n         ${value}\n       </div>\n </div>\n</template>\n`,\n  props:["data"]\n}',
      numberFormat: null,
      children: [],
      attributes: {
        rowspan: 2,
        sortable: null,
      },
      id: 41140,
    },
    {
      dataField: 'doc_date',
      sortOrder: 15,
      link: null,
      title: 'яратилган<br>сана',
      sumType: null,
      hint: null,
      width: null,
      formatCondition: '',
      formatColor: '',
      formatBackgroundColor: '',
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'center',
      footerAlign: 'center',
      cellFormat:
        'return {\ntemplate: `\n<template>\n <div>\n       <div v-if="data.num == null" style="font-weight: 700">\n         ${value}\n       </div>\n       <div  v-else>\n         ${value}\n       </div>\n </div>\n</template>\n`,\n  props:["data"]\n}',
      numberFormat: null,
      children: [],
      attributes: {
        rowspan: 2,
        sortable: null,
      },
      id: 41133,
    },
    {
      dataField: 'name',
      sortOrder: 20,
      link: null,
      title: 'фамилияси, исми, шарифи',
      sumType: null,
      hint: null,
      width: '330',
      formatCondition: '',
      formatColor: '',
      formatBackgroundColor: '',
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'left',
      footerAlign: 'right',
      cellFormat:
        'return {\n  template: `\n    <div class="mx-auto d-flex align-items-center" style="font-weight: 700;">\n    <div @click="() => isVisible = !isVisible">\n    \t<img style=\'margin-right: 8px; border-radius: 50%; width: 45px; height: 45px; object-fit: cover; border: 1px solid #d7d7d7; padding: 2px; transition: .2s; cursor: pointer;\' :src="data.main_image" />\n    </div>  \n    <div v-if="isVisible" @click="() => isVisible = !isVisible" class="enlarged_picture">\n    \t<img :src="data.main_image" />\n    </div>\n      <p style="margin-bottom:0;">  {{value}} </p>\n    </div>`,\n\n  props:["data","value"],\n  data() {\n    return {\n      imgId: [],\n      isVisible: false\n    }\n  }\n} ',
      numberFormat: null,
      children: [],
      attributes: {
        rowspan: 2,
        sortable: false,
      },
      id: 41135,
    },
    {
      dataField: 'department',
      sortOrder: 30,
      link: null,
      title: 'таркибий тузилма номи',
      sumType: null,
      hint: null,
      width: '220',
      formatCondition: '',
      formatColor: '',
      formatBackgroundColor: '',
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'left',
      footerAlign: 'center',
      cellFormat:
        'return {\ntemplate: `\n<template>\n <div>\n       <div v-if="data.num == null" style="font-weight: 700">\n         ${value}\n       </div>\n       <div  v-else>\n         ${value}\n       </div>\n </div>\n</template>\n`,\n  props:["data"]\n}',
      numberFormat: null,
      children: [],
      attributes: {
        rowspan: 2,
        sortable: null,
      },
      id: 41132,
    },
    {
      dataField: 'position',
      sortOrder: 40,
      link: null,
      title: 'лавозим номи',
      sumType: null,
      hint: null,
      width: '200',
      formatCondition: '',
      formatColor: '',
      formatBackgroundColor: '',
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'left',
      footerAlign: 'center',
      cellFormat:
        'return {\ntemplate: `\n<template>\n <div>\n       <div v-if="data.num == null" style="font-weight: 700">\n         ${value}\n       </div>\n       <div  v-else>\n         ${value}\n       </div>\n </div>\n</template>\n`,\n  props:["data"]\n}',
      numberFormat: null,
      children: [],
      attributes: {
        rowspan: 2,
        sortable: null,
      },
      id: 41139,
    },
    {
      dataField: 'structure',
      sortOrder: 50,
      link: null,
      title: 'ставка',
      sumType: null,
      hint: null,
      width: null,
      formatCondition: '',
      formatColor: '',
      formatBackgroundColor: '',
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'center',
      footerAlign: 'center',
      cellFormat:
        'return {\ntemplate: `\n<template>\n <div>\n       <div v-if="data.num == null" style="font-weight: 700">\n         ${value}\n       </div>\n       <div  v-else>\n         ${value}\n       </div>\n </div>\n</template>\n`,\n  props:["data"]\n}',
      numberFormat: null,
      children: [],
      attributes: {
        rowspan: 2,
        sortable: null,
      },
      id: 41143,
    },
    {
      dataField: null,
      sortOrder: 61,
      link: null,
      title: 'ариза',
      sumType: null,
      hint: null,
      width: null,
      formatCondition: null,
      formatColor: null,
      formatBackgroundColor: null,
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'center',
      footerAlign: 'center',
      cellFormat: null,
      numberFormat: null,
      children: [
        {
          dataField: 'sum_s1',
          sortOrder: 50,
          link: null,
          title: 'қиймати<br>(сўм)',
          sumType: null,
          hint: null,
          width: null,
          formatCondition: null,
          formatColor: null,
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat:
            'return {\ntemplate: `\n<template>\n <div>\n       <div v-if="data.num == null" style="font-weight: 700">\n         ${value}\n       </div>\n       <div  v-else>\n         ${value}\n       </div>\n </div>\n</template>\n`,\n  props:["data"]\n}',
          numberFormat: 3,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 42460,
        },
        {
          dataField: 'period_s1',
          sortOrder: 60,
          link: null,
          title: 'муддат<br>(ой)',
          sumType: null,
          hint: null,
          width: null,
          formatCondition: null,
          formatColor: null,
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat:
            'return {\ntemplate: `\n<template>\n <div>\n       <div v-if="data.num == null" style="font-weight: 700">\n         ${value}\n       </div>\n       <div  v-else>\n         ${value}\n       </div>\n </div>\n</template>\n`,\n  props:["data"]\n}',
          numberFormat: null,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 42459,
        },
        {
          dataField: 's1',
          sortOrder: 70,
          link: null,
          title: 'ходим имзолаган <br> сана',
          sumType: null,
          hint: null,
          width: null,
          formatCondition: '',
          formatColor: '',
          formatBackgroundColor: '',
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat:
            "return {\n  template: `\n    <template>\n      <div>\n        <div v-if=\"data.num == null\" style=\"font-weight: 700; cursor:pointer; text-decoration: underline;\" @click='openTable'>\n          ${value}\n        </div>\n        <div v-else style=\"text-decoration: underline; cursor:pointer;\" @click='openTable'>\n          ${value}\n        </div>\n      </div>\n    </template>\n  `,\n  inject: ['table'],\n  props: ['value', 'data', 'col', 'params'],\n  data: () => ({\n    selected: null,\n    loading: false,\n    file: '',\n    translateDoc: this.$l('document-status-doc', 'Ушбу шартномага файл бириктирилмаган.')\n    \n  }),\n\n  methods: {\n    openTable() {\n      this.$root.navigateTo(this.data.doc_link);\n      \n      \n      this.$api.get(`sm-applications-get-file?id=${data.id}`).then((res) => {\n        this.file = res.data.data.file;\n        if (data.doc_link == null) {\n          if (this.file == null) {\n            this.$platonApp.errorToast(this.translateDoc);\n          } else {\n            window.open(`https://smart-office.uz/uploads/files/${this.file}`);\n          }\n        } else {\n          window.open(data.doc_link);\n        }\n      });\n    }\n  }\n};\n",
          numberFormat: null,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 41148,
        },
        {
          dataField: 's3',
          sortOrder: 75,
          link: null,
          title: 'ходим раҳбари <br> томонидан <br> имзоланган сана',
          sumType: null,
          hint: null,
          width: null,
          formatCondition: null,
          formatColor: null,
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat:
            "return {\n  template: `\n    <template>\n      <div>\n        <div v-if=\"data.num == null\" style=\"font-weight: 700; cursor:pointer; text-decoration: underline;\" @click='openTable'>\n          ${value}\n        </div>\n        <div v-else style=\"text-decoration: underline; cursor:pointer;\" @click='openTable'>\n          ${value}\n        </div>\n      </div>\n    </template>\n  `,\n  inject: ['table'],\n  props: ['value', 'data', 'col', 'params'],\n  data: () => ({\n    selected: null,\n    loading: false,\n    translate: this.$l('hujjat-imzolanmagan', 'Хужжат имзоланмаган!!!'),\n    file: ''\n  }),\n\n  methods: {\n    openTable() {\n      this.$root.navigateTo(this.data.doc_link);\n      \n      \n      // this.$api.get(`sm-applications-get-file?id=${data.id}`).then((res) => {\n      //   this.file = res.data.data.file;\n      //   if (data.doc_link == null) {\n      //     if (this.file == null) {\n      //       this.$platonApp.errorToast(this.translateDoc);\n      //     } else {\n      //       window.open(`https://smart-office.uz/uploads/files/${this.file}`);\n      //     }\n      //   } else {\n      //     window.open(data.doc_link);\n      //   }\n      // });\n    }\n  }\n};\n",
          numberFormat: null,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 43943,
        },
        {
          dataField: 's2',
          sortOrder: 80,
          link: null,
          title: 'раҳбар имзолаган <br> сана',
          sumType: null,
          hint: null,
          width: null,
          formatCondition: '',
          formatColor: '',
          formatBackgroundColor: '',
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat:
            "return {\n  template: `\n    <template>\n      <div>\n        <div v-if=\"data.num == null\" style=\"font-weight: 700; cursor:pointer; text-decoration: underline;\" @click='openTable'>\n          ${value}\n        </div>\n        <div v-else style=\"text-decoration: underline; cursor:pointer;\" @click='openTable'>\n          ${value}\n        </div>\n      </div>\n    </template>\n  `,\n  inject: ['table'],\n  props: ['value', 'data', 'col', 'params'],\n  data: () => ({\n    selected: null,\n    loading: false,\n    translate: this.$l('hujjat-imzolanmagan', 'Хужжат имзоланмаган!!!'),\n    file: ''\n  }),\n\n  methods: {\n    openTable() {\n      this.$root.navigateTo(this.data.doc_link);\n      \n      \n      // this.$api.get(`sm-applications-get-file?id=${data.id}`).then((res) => {\n      //   this.file = res.data.data.file;\n      //   if (data.doc_link == null) {\n      //     if (this.file == null) {\n      //       this.$platonApp.errorToast(this.translateDoc);\n      //     } else {\n      //       window.open(`https://smart-office.uz/uploads/files/${this.file}`);\n      //     }\n      //   } else {\n      //     window.open(data.doc_link);\n      //   }\n      // });\n    }\n  }\n};\n",
          numberFormat: null,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 41149,
        },
      ],
      attributes: {
        rowspan: null,
        sortable: null,
      },
      id: 41147,
    },
    {
      dataField: null,
      sortOrder: 62,
      link: null,
      title: 'шартнома',
      sumType: null,
      hint: null,
      width: null,
      formatCondition: null,
      formatColor: null,
      formatBackgroundColor: null,
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'center',
      footerAlign: 'center',
      cellFormat: null,
      numberFormat: null,
      children: [
        {
          dataField: 'sum_s2',
          sortOrder: 70,
          link: null,
          title: 'қиймати<br>(сўм)',
          sumType: null,
          hint: 'қиймати<br>(сўм)',
          width: null,
          formatCondition: null,
          formatColor: null,
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat:
            'return {\ntemplate: `\n<template>\n <div>\n       <div v-if="data.num == null" style="font-weight: 700">\n         ${value}\n       </div>\n       <div  v-else>\n         ${value}\n       </div>\n </div>\n</template>\n`,\n  props:["data"]\n}',
          numberFormat: 3,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 42461,
        },
        {
          dataField: 'period_s2',
          sortOrder: 80,
          link: null,
          title: 'муддат<br>(ой)',
          sumType: null,
          hint: null,
          width: null,
          formatCondition: null,
          formatColor: null,
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat:
            'return {\ntemplate: `\n<template>\n <div>\n       <div v-if="data.num == null" style="font-weight: 700">\n         ${value}\n       </div>\n       <div  v-else>\n         ${value}\n       </div>\n </div>\n</template>\n`,\n  props:["data"]\n}',
          numberFormat: null,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 42462,
        },
        {
          dataField: 'c1',
          sortOrder: 90,
          link: null,
          title: 'ходим имзолаган <br> сана',
          sumType: null,
          hint: null,
          width: null,
          formatCondition: null,
          formatColor: null,
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat:
            "return {\n  template: `\n    <template>\n      <div>\n        <div v-if=\"data.num == null\" style=\"font-weight: 700; cursor:pointer; text-decoration: underline;\" @click='openTable'>\n          ${value}\n        </div>\n        <div v-else style=\"text-decoration: underline; cursor:pointer;\" @click='openTable'>\n          ${value}\n        </div>\n      </div>\n    </template>\n  `,\n  inject: ['table'],\n  props: ['value', 'data', 'col', 'params'],\n  data: () => ({\n    selected: null,\n    loading: false,\n    file: '',\n    translateDoc:this.$l('document-status-doc', 'Ушбу шартномага файл бириктирилмаган.')\n    \n  }),\n\n  methods: {\n    openTable() {\n      this.$root.navigateTo(this.data.doc_link_c);\n      \n      \n      // this.$api.get(`sm-applications-get-file?id=${data.id}`).then((res) => {\n      //   this.file = res.data.data.file;\n      //   if (data.doc_link == null) {\n      //     if (this.file == null) {\n      //       this.$platonApp.errorToast(this.translateDoc);\n      //     } else {\n      //       window.open(`https://smart-office.uz/uploads/files/${this.file}`);\n      //     }\n      //   } else {\n      //     window.open(data.doc_link);\n      //   }\n      // });\n    }\n  }\n};\n",
          numberFormat: null,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 41151,
        },
        {
          dataField: 'c2',
          sortOrder: 100,
          link: null,
          title: 'раҳбар имзолаган <br>сана',
          sumType: null,
          hint: null,
          width: null,
          formatCondition: null,
          formatColor: null,
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat:
            "return {\n  template: `\n    <template>\n      <div>\n        <div v-if=\"data.num == null\" style=\"font-weight: 700; cursor:pointer; text-decoration: underline;\" @click='openTable'>\n          ${value}\n        </div>\n        <div v-else style=\"text-decoration: underline; cursor:pointer;\" @click='openTable'>\n          ${value}\n        </div>\n      </div>\n    </template>\n  `,\n  inject: ['table'],\n  props: ['value', 'data', 'col', 'params'],\n  data: () => ({\n    selected: null,\n    loading: false,\n    file: '',\n    translateDoc:this.$l('document-status-doc', 'Ушбу шартномага файл бириктирилмаган.')\n    \n  }),\n\n  methods: {\n    openTable() {\n      this.$root.navigateTo(this.data.doc_link_c);\n      \n      \n      // this.$api.get(`sm-applications-get-file?id=${data.id}`).then((res) => {\n      //   this.file = res.data.data.file;\n      //   if (data.doc_link == null) {\n      //     if (this.file == null) {\n      //       this.$platonApp.errorToast(this.translateDoc);\n      //     } else {\n      //       window.open(`https://smart-office.uz/uploads/files/${this.file}`);\n      //     }\n      //   } else {\n      //     window.open(data.doc_link);\n      //   }\n      // });\n    }\n  }\n};\n",
          numberFormat: null,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 41152,
        },
      ],
      attributes: {
        rowspan: null,
        sortable: null,
      },
      id: 41150,
    },
    {
      dataField: 'doc_status',
      sortOrder: 130,
      link: null,
      title: 'ҳолати',
      sumType: null,
      hint: null,
      width: null,
      formatCondition: '',
      formatColor: '',
      formatBackgroundColor: '',
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'center',
      footerAlign: 'center',
      cellFormat:
        'return value == 0 ? `<div class="badge font-weight-bold bg-danger text-white">бекор қилинган</div>`\n    : (value == 3 ? `<div class="badge font-weight-bold bg-success text-white">имзоланган</div>` :\n        (value == 2 ? `<div class="badge font-weight-bold bg-warning text-white">жараёнда</div>` :\n            (value == 1 ? `<div class="badge font-weight-bold bg-secondary text-white">имзоланмаган</div>` :\n                `<div class="badge font-weight-bold bg-dark text-white">ҳужжат йўқ</div>`)))',
      numberFormat: null,
      children: [],
      attributes: {
        rowspan: null,
        sortable: null,
      },
      id: 41134,
    },
    {
      dataField: '',
      sortOrder: 132,
      link: null,
      title: 'ҳисобот',
      sumType: null,
      hint: 'ҳисобот',
      width: null,
      formatCondition: null,
      formatColor: null,
      formatBackgroundColor: null,
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'center',
      footerAlign: 'center',
      cellFormat:
        'return {\ntemplate: `\n<template>\n <div>\n       <div v-if="data.num == null" style="font-weight: 700">\n         ${value}\n       </div>\n       <div  v-else>\n         ${value}\n       </div>\n </div>\n</template>\n`,\n  props:["data"]\n}',
      numberFormat: null,
      children: [
        {
          dataField: 'remainder',
          sortOrder: 150,
          link: null,
          title: 'қолган сумма(сўм)',
          sumType: null,
          hint: 'қолган сумма',
          width: '120',
          formatCondition: null,
          formatColor: null,
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat:
            "return {\ntemplate: `\n<template>\n <div>\n        <div v-if=\"data.remainder == null\" style=\"font-weight: 700\">\n         0\n       </div>\n       <div v-else-if=\"data.num == null\" style=\"font-weight: 700\">\n         ${value}\n       </div>\n       <div v-else>\n         ${value}\n       </div>\n </div>\n</template>\n`,\n   inject: ['table'],\n  props: ['value', 'data', 'col', 'params'],\n  data: () => ({\n    selected: null,\n    loading: false,\n    file: '',\n    translateDoc:this.$l('document-status-doc', 'Ушбу шартномага файл бириктирилмаган.')\n    \n  }),\n  mounted(){\n    \n  },\n\n  methods: {\n    \n  }\n}",
          numberFormat: 3,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 42465,
        },
        {
          dataField: 'procent_remainder',
          sortOrder: 160,
          link: null,
          title: 'қолган қисми(%)',
          sumType: null,
          hint: 'қолган қисми',
          width: '70',
          formatCondition: null,
          formatColor: null,
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat:
            'return {\ntemplate: `\n<template>\n <div>\n        <div v-if="data.procent_remainder == null" style="font-weight: 700">\n         0\n       </div>\n       <div v-else-if="data.num == null" style="font-weight: 700">\n         ${value}\n       </div>\n       <div  v-else>\n         ${value}\n       </div>\n </div>\n</template>\n`,\n  props:["data"]\n}',
          numberFormat: null,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 42466,
        },
        {
          dataField: 'part',
          sortOrder: 170,
          link: null,
          title: 'тўланган сумма (сўм)',
          sumType: null,
          hint: 'тўланган сумма',
          width: '120',
          formatCondition: null,
          formatColor: null,
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat:
            'return {\ntemplate: `\n<template>\n <div>\n        <div v-if="data.part == null" style="font-weight: 700">\n         0\n       </div>\n       <div v-else-if="data.num == null" style="font-weight: 700">\n         ${value}\n       </div>\n       <div  v-else>\n         ${value}\n       </div>\n </div>\n</template>\n`,\n  props:["data"]\n}',
          numberFormat: 3,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 42467,
        },
        {
          dataField: 'procent_part',
          sortOrder: 180,
          link: null,
          title: 'тўланган қисми (%)',
          sumType: null,
          hint: 'тўланган қисми',
          width: '100',
          formatCondition: null,
          formatColor: null,
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat:
            'return {\ntemplate: `\n<template>\n <div>\n        <div v-if="data.procent_part == null" style="font-weight: 700">\n         0\n       </div>\n       <div v-else-if="data.num == null" style="font-weight: 700">\n         ${value}\n       </div>\n       <div  v-else>\n         ${value}\n       </div>\n </div>\n</template>\n`,\n  props:["data"]\n}',
          numberFormat: 3,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 42468,
        },
      ],
      attributes: {
        rowspan: null,
        sortable: null,
      },
      id: 42464,
    },
  ],
  filters: [
    {
      id: 4345,
      tableName: 'applications-accounting-modified',
      tableLevel: 1,
      key: 'staff_name',
      type: 'text',
      defaultValue: null,
      sortOrder: 5,
      title: 'қидирув...',
      width: 2,
      cssClass: null,
      cssStyle: null,
      position: 'bottom-left',
      allowClear: true,
      data: [],
      attributes: {
        has_label: false,
        allow_clear: true,
      },
    },
    {
      id: 4632,
      tableName: 'applications-accounting-modified',
      tableLevel: 1,
      key: 'org_id',
      type: 'select',
      defaultValue: '303465075',
      sortOrder: 9,
      title: null,
      width: 2,
      cssClass: null,
      cssStyle: null,
      position: 'bottom-left',
      allowClear: false,
      data: [
        {
          id: null,
          name: 'Tashkilot',
        },
        {
          id: 309095650,
          name: '«SMART MARKETPLACE» АJ',
        },
        {
          id: 307261969,
          name: '«AGROONLINE» MCHJ',
        },
        {
          id: 310900156,
          name: '«REALSOFT SAMARKAND» MCHJ',
        },
        {
          id: 311161546,
          name: '«REALSOFT AI» MCHJ',
        },
        {
          id: 311210365,
          name: '«REALSOFT NAMANGAN» MCHJ ',
        },
        {
          id: 310704139,
          name: 'REALSOFT BUKHARA MCHJ',
        },
        {
          id: 309165096,
          name: '«WISESOFT IT GROUP» MCHJ ',
        },
        {
          id: 310256941,
          name: '«REALSOFT ACADEMY» MCHJ',
        },
        {
          id: 303465075,
          name: '«REALSOFT» MCHJ',
        },
      ],
      attributes: {
        has_label: 'false',
        allow_clear: 'false',
      },
    },
    {
      id: 4127,
      tableName: 'applications-accounting-modified',
      tableLevel: 1,
      key: 'filter_app_doc_type',
      type: 'select',
      defaultValue: null,
      sortOrder: 10,
      title: 'Ариза турлари',
      width: 2,
      cssClass: null,
      cssStyle: null,
      position: 'bottom-left',
      allowClear: true,
      data: [
        {
          id: null,
          name: 'ariza turlari',
        },
        {
          id: 8,
          name: 'Foizsiz qarz berish',
        },
      ],
      attributes: {
        has_label: null,
        allow_clear: true,
      },
    },
    {
      id: 4128,
      tableName: 'applications-accounting-modified',
      tableLevel: 1,
      key: 'filter_doc_status_app',
      type: 'select',
      defaultValue: '',
      sortOrder: 20,
      title: 'досумент ҳолати',
      width: 2,
      cssClass: null,
      cssStyle: null,
      position: 'bottom-left',
      allowClear: true,
      data: [
        {
          id: null,
          name: 'ariza holati',
        },
        {
          id: 4,
          name: 'hammasi',
        },
        {
          id: 0,
          name: 'bekor qilingan',
        },
        {
          id: 1,
          name: 'imzolanmagan',
        },
        {
          id: 2,
          name: 'jarayonda',
        },
        {
          id: 3,
          name: 'imzolangan',
        },
      ],
      attributes: {
        has_label: null,
        allow_clear: true,
      },
    },
  ],
  buttons: [
    {
      id: 3663,
      tableName: 'applications-accounting-modified',
      tableLevel: 1,
      type: 'link',
      title: 'қўшиш',
      sortOrder: 110,
      width: 2,
      cssClass: null,
      cssStyle: null,
      iconClass: 'fas fa-plus-circle',
      link: 'forms/check_application_accounting-modified?_level=1&o=303465075&_target=modal_30',
      js: null,
      position: 'bottom-right',
      shortKeyLabel: null,
      hasDividerBefore: null,
      exportResourceName: null,
      excelImportConfigId: null,
      attributes: {},
    },
  ],
  attributes: {
    notification_event: null,
  },
  params: {
    staff_name: null,
    search: '',
    user_pinfl: 33105985580014,
    order_filter: 3,
    filter_department: '',
    level: null,
    org_id: 303465075,
    doc_status: 4,
    gr_name: '0',
    id: 'fc4d8185-ca25-451a-bd61-2e3a3e38bca5',
    projectId: 1,
    chief_accountant: false,
  },
}
</script>
