<template>
  <div class="max-w-7xl mx-auto p-4">
    <BaseTable
      :columns="tableMetadata.columns"
      :data="processedEmployeeData"
      :metadata="tableMetadata"
      :show-summary="true"
    />
  </div>
</template>
<script lang="ts" setup>
import { computed } from 'vue'
import BaseTable from '@/components/BaseTable.vue'

// Your original employee data
const rawEmployeeData = [
  {
    name: 'Худайбердиев Беҳзод Дилшод ўғли',
    name1: "XUDAYBERDIYEV BEHZOD DILSHOD O'G'LI",
    given_org_id: 303465075,
    work_org_id: 303465075,
    staff_salary_id: 'ccef9859-29e5-6b74-da8f-dbc6dce81478',
    bdate: '01.09.2025',
    edate: '23.09.2025',
    last_date_of_previous_month: '2025-08-31',
    first_date_of_previous_month: '2025-08-01',
    end_date: '2025-08-31',
    state: 'ESTIMATED',
    staff_id: '161b4b89-8239-49a1-b409-04345505111f',
    status: 1,
    int10: 1,
    num04: 1500,
    num05: 18637500,
    p_num: '41',
    letter_index: '141',
    pinfl: 33105985580014,
    category: 'Fix1500',
    category_id: '887ed769-1da9-4f95-f688-200ac138429b',
    rate: 0,
    planned_time: 128,
    work_time_norm: 128,
    estimated_time: 0,
    monthly_lunch_total: 375000,
    monthly_lunch_sale: 0,
    monthly_lunch_calculated: 375000,
    estimated_percent: 0,
    new_salary_usd: 0,
    new_salary_uzs: 14285720,
    vacation_pay_usd: 0,
    vacation_pay_uzs: 0,
    avans_prepayment: 0,
    worked_hours: 160.81,
    worked_percent: 0,
    days_count: 16,
    vacation_day: 0,
    vacation_work_time: 0,
    vacation_work_time_limit: 0,
    previous_month_balance: 0,
    department: "Sifat bo'yicha departamenti",
    gr: "Sifat bo'yicha departamenti",
    vacation: null,
    dayly_hours: 8,
    changes_attendance: 14285720,
    hundred_percent: 14285720,
    half_month_calc: 14285720,
    half_month_tax: 1071429,
    half_month_loan: 0,
    half_month_privilege: 0,
    half_month_lunch_total: 375000,
    half_month_lunch_sale: 0,
    half_month_lunch: 375000,
    monthly_calc: 14285720,
    monthly_tax: 1071429,
    monthly_pay: 12839291,
    half_month_pay: 12839291,
    overpayment: 0,
    confirmed_excess_sum: 0,
    unconfirmed_excess_sum: 0,
    pay_overpayment: 0,
    avans_calc: 0,
    avans_tax: 0,
    avans_loan: 0,
    avans_lunch: 0,
    avans_lunch_sale: 0,
    avans_lunch_total: 0,
    avans_pay: 0,
    org_id: 303465075,
    old_salary: 18750000,
    avans_privilege: 0,
  },
]

// Process the data to add row numbers and any missing fields
const processedEmployeeData = computed(() => {
  return rawEmployeeData.map((employee, index) => ({
    ...employee,
    _rownum: index + 1,
    worked_percent:
      employee.work_time_norm > 0
        ? ((employee.worked_hours / employee.work_time_norm) * 100).toFixed(2)
        : 0,
    id: employee.staff_id || `emp_${index}`,
  }))
})

const tableMetadata = {
  title: '«REALSOFT» MCHJ ходимларининг ойлик харажатлари',
  groupingField: 'gr',
  leftFixed: 2,
  rightFixed: 0,
  columns: [
    {
      dataField: '_rownum',
      sortOrder: 10,
      link: null,
      title: '№',
      sumType: '@_count',
      hint: null,
      width: '30',
      formatCondition: null,
      formatColor: null,
      formatBackgroundColor: null,
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'center',
      footerAlign: 'center',
      cellFormat: '',
      numberFormat: null,
      children: [],
      attributes: {
        rowspan: null,
        sortable: null,
      },
      id: 44838,
    },
    {
      dataField: 'name',
      sortOrder: 20,
      link: null,
      title: 'Ф.И.Ш',
      sumType: 'жами:',
      hint: null,
      width: '350',
      formatCondition: null,
      formatColor: null,
      formatBackgroundColor: null,
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'left',
      footerAlign: 'center',
      cellFormat: '',
      numberFormat: null,
      children: [],
      attributes: {
        rowspan: null,
        sortable: null,
      },
      id: 44837,
    },
    {
      dataField: 'pinfl',
      sortOrder: 30,
      link: null,
      title: 'ЖШШИР',
      sumType: null,
      hint: null,
      width: '70',
      formatCondition: null,
      formatColor: null,
      formatBackgroundColor: null,
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'center',
      footerAlign: 'center',
      cellFormat: null,
      numberFormat: null,
      children: [],
      attributes: {
        rowspan: null,
        sortable: null,
      },
      id: 44836,
    },
    {
      dataField: 'category',
      sortOrder: 40,
      link: null,
      title: 'малака <br> даража',
      sumType: null,
      hint: null,
      width: '50',
      formatCondition: null,
      formatColor: null,
      formatBackgroundColor: null,
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'center',
      footerAlign: 'center',
      cellFormat: '',
      numberFormat: null,
      children: [],
      attributes: {
        rowspan: null,
        sortable: true,
      },
      id: 44841,
    },
    {
      dataField: 'days_count',
      sortOrder: 55,
      link: null,
      title: 'кун',
      sumType: '@_sum',
      hint: null,
      width: null,
      formatCondition: null,
      formatColor: null,
      formatBackgroundColor: null,
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'center',
      footerAlign: 'center',
      cellFormat: '',
      numberFormat: null,
      children: [],
      attributes: {
        rowspan: null,
        sortable: null,
      },
      id: 44839,
    },
    {
      dataField: 'planned_time',
      sortOrder: 58,
      link: null,
      title: 'меъёр',
      sumType: '@_sum',
      hint: null,
      width: null,
      formatCondition: null,
      formatColor: null,
      formatBackgroundColor: null,
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'center',
      footerAlign: 'center',
      cellFormat: null,
      numberFormat: 1,
      children: [],
      attributes: {
        rowspan: null,
        sortable: true,
      },
      id: 44835,
    },
    {
      dataField: null,
      sortOrder: 60,
      link: null,
      title: 'иш соатлари, соат',
      sumType: null,
      hint: null,
      width: null,
      formatCondition: null,
      formatColor: null,
      formatBackgroundColor: null,
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'center',
      footerAlign: 'center',
      cellFormat: null,
      numberFormat: null,
      children: [
        {
          dataField: 'estimated_time',
          sortOrder: 80,
          link: null,
          title: 'бажарил<br> ган',
          sumType: '@_sum',
          hint: null,
          width: null,
          formatCondition: '@worked_hours<@estimated_time',
          formatColor: 'red',
          formatBackgroundColor: 'rgb(243 228 165 / 37%)',
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat: '',
          numberFormat: 2,
          children: [],
          attributes: {
            rowspan: null,
            sortable: true,
          },
          id: 44834,
        },
        {
          dataField: 'estimated_percent',
          sortOrder: 90,
          link: null,
          title: 'фоиз <br> %',
          sumType: null,
          hint: null,
          width: null,
          formatCondition: '@estimated_percent < 50',
          formatColor: 'red',
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat: null,
          numberFormat: 2,
          children: [],
          attributes: {
            rowspan: null,
            sortable: true,
          },
          id: 44830,
        },
      ],
      attributes: {
        rowspan: null,
        sortable: null,
      },
      id: 44829,
    },
    {
      dataField: null,
      sortOrder: 110,
      link: null,
      title: 'давомат, соат',
      sumType: null,
      hint: null,
      width: null,
      formatCondition: null,
      formatColor: null,
      formatBackgroundColor: null,
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'center',
      footerAlign: 'center',
      cellFormat: null,
      numberFormat: null,
      children: [
        {
          dataField: 'worked_hours',
          sortOrder: 150,
          link: null,
          title: 'амалда',
          sumType: '@_sum',
          hint: null,
          width: null,
          formatCondition: null,
          formatColor: null,
          formatBackgroundColor: '',
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat: null,
          numberFormat: 2,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 44799,
        },
        {
          dataField: 'worked_percent',
          sortOrder: 160,
          link: null,
          title: 'фоиз %',
          sumType: '(@worked_hours/@work_time_norm)*100',
          hint: null,
          width: null,
          formatCondition: null,
          formatColor: null,
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat: null,
          numberFormat: 2,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 44798,
        },
      ],
      attributes: {
        rowspan: null,
        sortable: null,
      },
      id: 44797,
    },
    {
      dataField: null,
      sortOrder: 112,
      link: null,
      title: 'ҳисобланган <br> иш ҳақи',
      sumType: null,
      hint: null,
      width: null,
      formatCondition: null,
      formatColor: null,
      formatBackgroundColor: 'green',
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'center',
      footerAlign: 'center',
      cellFormat: null,
      numberFormat: null,
      children: [
        {
          dataField: 'new_salary_usd',
          sortOrder: 110,
          link: null,
          title: 'USD',
          sumType: '@_sum',
          hint: null,
          width: null,
          formatCondition: null,
          formatColor: null,
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat: null,
          numberFormat: 2,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 44846,
        },
        {
          dataField: 'hundred_percent',
          sortOrder: 118,
          link: null,
          title: 'SUM',
          sumType: '@_sum',
          hint: null,
          width: null,
          formatCondition: null,
          formatColor: '#000000',
          formatBackgroundColor: '#b8ffb8',
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat: null,
          numberFormat: 2,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 44845,
        },
      ],
      attributes: {
        rowspan: null,
        sortable: null,
      },
      id: 44844,
    },
    {
      dataField: '',
      sortOrder: 122,
      link: null,
      title: 'ҳисобланган <br> меҳнат таътили',
      sumType: null,
      hint: null,
      width: null,
      formatCondition: null,
      formatColor: null,
      formatBackgroundColor: null,
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'center',
      footerAlign: 'center',
      cellFormat: null,
      numberFormat: null,
      children: [
        {
          dataField: 'vacation_day',
          sortOrder: 40,
          link: null,
          title: 'кун',
          sumType: '@_sum',
          hint: null,
          width: null,
          formatCondition: '@vacation_day > 0',
          formatColor: '#f39834',
          formatBackgroundColor: '',
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat: '',
          numberFormat: null,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 44775,
        },
        {
          dataField: 'vacation_pay_uzs',
          sortOrder: 250,
          link: null,
          title: 'SUM',
          sumType: '@_sum',
          hint: null,
          width: null,
          formatCondition: '@vacation_pay_uzs > 0',
          formatColor: '#f39834',
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat: '',
          numberFormat: 2,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 44774,
        },
      ],
      attributes: {
        rowspan: null,
        sortable: null,
      },
      id: 44772,
    },
    {
      dataField: 'previous_month_balance',
      sortOrder: 125,
      link: null,
      title: 'қўшимча <br> ҳақ',
      sumType: '@_sum',
      hint: null,
      width: null,
      formatCondition: null,
      formatColor: null,
      formatBackgroundColor: null,
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'center',
      footerAlign: 'center',
      cellFormat: '',
      numberFormat: 2,
      children: [],
      attributes: {
        rowspan: null,
        sortable: null,
      },
      id: 44842,
    },
    {
      dataField: 'monthly',
      sortOrder: 130,
      link: null,
      title: 'умумий',
      sumType: null,
      hint: null,
      width: null,
      formatCondition: null,
      formatColor: null,
      formatBackgroundColor: null,
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'center',
      footerAlign: 'center',
      cellFormat: null,
      numberFormat: 1,
      children: [
        {
          dataField: 'monthly_calc',
          sortOrder: 300,
          link: null,
          title: 'ҳисобланди',
          sumType: '@_sum',
          hint: null,
          width: null,
          formatCondition: '',
          formatColor: '',
          formatBackgroundColor: '#fff0ad',
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat: null,
          numberFormat: 2,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 44820,
        },
        {
          dataField: 'half_month_privilege',
          sortOrder: 305,
          link: null,
          title: 'имтиёз',
          sumType: '@_sum',
          hint: null,
          width: null,
          formatCondition: null,
          formatColor: null,
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat: '',
          numberFormat: 2,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 44828,
        },
        {
          dataField: 'monthly_tax',
          sortOrder: 310,
          link: null,
          title: 'даромад <br>  солиғи',
          sumType: '@_sum',
          hint: null,
          width: null,
          formatCondition: '@monthly_tax < 0',
          formatColor: 'red',
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat: null,
          numberFormat: 2,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 44825,
        },
        {
          dataField: 'monthly_lunch_calculated',
          sortOrder: 320,
          link: null,
          title: 'тушлик',
          sumType: '@_sum',
          hint: null,
          width: null,
          formatCondition: null,
          formatColor: null,
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat: null,
          numberFormat: 0,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 44817,
        },
        {
          dataField: 'half_month_loan',
          sortOrder: 321,
          link: null,
          title: 'фоизсиз <br>қарз',
          sumType: '@_sum',
          hint: null,
          width: null,
          formatCondition: null,
          formatColor: null,
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat: '',
          numberFormat: 2,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 44819,
        },
        {
          dataField: 'avans_prepayment',
          sortOrder: 322,
          link: null,
          title: 'олдиндан <br> тўлов',
          sumType: '@_sum',
          hint: null,
          width: null,
          formatCondition: null,
          formatColor: null,
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat: '',
          numberFormat: 2,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 44818,
        },
        {
          dataField: 'avans_pay',
          sortOrder: 325,
          link: null,
          title: 'тўланган',
          sumType: '@_sum',
          hint: null,
          width: null,
          formatCondition: null,
          formatColor: '#000000',
          formatBackgroundColor: '#b8ffb8',
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat: '',
          numberFormat: 2,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 44826,
        },
        {
          dataField: 'half_month_pay',
          sortOrder: 460,
          link: null,
          title: 'якуний <br> тўлашга',
          sumType: '@_sum',
          hint: null,
          width: null,
          formatCondition: null,
          formatColor: '#000000',
          formatBackgroundColor: '#b8ffb8',
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat: null,
          numberFormat: 2,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 44816,
        },
      ],
      attributes: {
        rowspan: null,
        sortable: null,
      },
      id: 44815,
    },
    {
      dataField: 'overpayment2',
      sortOrder: 470,
      link: null,
      title: 'кейинги хисобот даврига',
      sumType: '@_sum',
      hint: null,
      width: null,
      formatCondition: null,
      formatColor: null,
      formatBackgroundColor: null,
      dataNowrap: null,
      footerNowrap: null,
      dataAlign: 'center',
      footerAlign: 'center',
      cellFormat: null,
      numberFormat: 2,
      children: [
        {
          dataField: 'overpayment',
          sortOrder: 510,
          link: null,
          title: 'ҳисобланди',
          sumType: '@_sum',
          hint: null,
          width: null,
          formatCondition: null,
          formatColor: null,
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat: null,
          numberFormat: 2,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 44783,
        },
        {
          dataField: 'confirmed_excess_sum',
          sortOrder: 520,
          link: null,
          title: 'тасдиқланди',
          sumType: '@_sum',
          hint: null,
          width: null,
          formatCondition: null,
          formatColor: '#000000',
          formatBackgroundColor: '#b8ffb8',
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat: null,
          numberFormat: 2,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 44782,
        },
        {
          dataField: 'unconfirmed_excess_sum',
          sortOrder: 530,
          link: null,
          title: 'тасдиқланмади',
          sumType: '@_sum',
          hint: null,
          width: null,
          formatCondition: null,
          formatColor: null,
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat: null,
          numberFormat: 2,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 44784,
        },
        {
          dataField: 'pay_overpayment',
          sortOrder: 540,
          link: null,
          title: 'тўлашга',
          sumType: '@_sum',
          hint: null,
          width: null,
          formatCondition: null,
          formatColor: null,
          formatBackgroundColor: null,
          dataNowrap: null,
          footerNowrap: null,
          dataAlign: 'center',
          footerAlign: 'center',
          cellFormat: null,
          numberFormat: 2,
          children: [],
          attributes: {
            rowspan: null,
            sortable: null,
          },
          id: 44785,
        },
      ],
      attributes: {
        rowspan: null,
        sortable: true,
      },
      id: 44781,
    },
  ],
  buttons: [],
}
</script>

